#
# Copyright (c) 2016 Tesora Inc.  All Rights Reserved.
#
# All use, reproduction, transfer, publication or disclosure is prohibited
# except as may be expressly permitted in the applicable license agreement.
#

- id: tesora-dbaas
  type: group
  role: [tesora-dbaas]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks:
    - fuel_pkgs
    - hiera
    - globals
    - logging
    - tools
    - netconfig
    - hosts
    - ssl-dns-setup
    - ssl-keys-saving
    - ssl-add-trust-chain
    - firewall
  parameters:
    strategy:
      type: parallel

- id: tesora-dbaas-configure-repo
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller, tesora-dbaas]
  requires: [deploy_start]
  required_for: [primary-heat, heat, deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/repo.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-haproxy
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [deploy_start, cluster-haproxy, openstack-haproxy]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/haproxy.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-haproxy-mistral
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [deploy_start, cluster-haproxy, openstack-haproxy]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/haproxy_mistral.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-db
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [primary-database, database]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/db.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-db-mistral
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [primary-database, database]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/db_mistral.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-keystone
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [primary-keystone, keystone]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/keystone.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-keystone-mistral
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [primary-keystone, keystone]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/keystone_mistral.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-install-packages
  version: 2.0.0
  type: puppet
  groups: [tesora-dbaas]
  requires: [deploy_start, tesora-dbaas-configure-repo, heat, horizon]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/install.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-install-packages-mistral
  version: 2.0.0
  type: puppet
  groups: [tesora-dbaas]
  requires: [deploy_start, tesora-dbaas-configure-repo, heat, horizon]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/install_mistral.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-rabbitmq
  version: 2.0.0
  type: puppet
  groups: [tesora-dbaas]
  requires: [tesora-dbaas-rabbitmq-cluster]
  parameters:
    puppet_manifest: puppet/manifests/rabbitmq.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-rabbitmq-cluster
  version: 2.0.0
  type: puppet
  groups: [tesora-dbaas]
  requires: [hosts, firewall, deploy_start]
  parameters:
    puppet_manifest: puppet/manifests/cluster.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-configure
  version: 2.0.0
  type: puppet
  groups: [tesora-dbaas]
  requires: [rabbitmq, tesora-dbaas-rabbitmq, tesora-dbaas-db-sync]
  required_for: [deploy_end]
  cross-depends:
    - name: tesora-dbaas-keystone
    - name: tesora-dbaas-db
  parameters:
    puppet_manifest: puppet/manifests/configure.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-configure-mistral
  version: 2.0.0
  type: puppet
  groups: [tesora-dbaas]
  requires: [rabbitmq, tesora-dbaas-rabbitmq, tesora-dbaas-install-packages-mistral, tesora-dbaas-install-packages, tesora-dbaas-configure]
  required_for: [deploy_end]
  cross-depends:
    - name: tesora-dbaas-keystone-mistral
    - name: tesora-dbaas-db-mistral
  parameters:
    puppet_manifest: puppet/manifests/configure_mistral.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-db-sync
  version: 2.0.0
  type: puppet
  groups: [tesora-dbaas]
  requires: [tesora-dbaas-install-packages]
  required_for: [deploy_end]
  cross-depends:
    - name: tesora-dbaas-db
  parameters:
    puppet_manifest: puppet/manifests/db_sync.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-db-sync-mistral
  version: 2.0.0
  type: puppet
  groups: [tesora-dbaas]
  requires: [tesora-dbaas-configure-mistral]
  required_for: [deploy_end]
  cross-depends:
    - name: tesora-dbaas-db-mistral
  parameters:
    puppet_manifest: puppet/manifests/db_sync_mistral.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-workbook-create
  version: 2.0.0
  type: puppet
  groups: [tesora-dbaas]
  requires: [tesora-dbaas-configure-mistral, tesora-dbaas-db-sync-mistral]
  required_for: [deploy_end]
  cross-depends:
    - name: tesora-dbaas-haproxy-mistral
  parameters:
    puppet_manifest: puppet/manifests/workbook_create.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: tesora-dbaas-horizon
  version: 2.0.0
  type: puppet
  groups: [primary-controller, controller]
  requires: [horizon]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/install_horizon.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800
