attributes:
  metadata:
    label: 'Tesora DBaaS Platform'
    group: 'other'

  tesora_guest_download_username:
    value: ''
    label: 'Username'
    description: 'Tesora DBaaS Platform username'
    weight: 70
    type: 'text'

  tesora_guest_download_password:
    value: ''
    label: 'Password'
    description: 'Tesora DBaaS Platform password'
    weight: 80
    type: 'password'

  tesora_accept_terms:
    weight: 90
    value: 'type "I AGREE"'
    label: 'Tesora DBaaS Terms Of Use'
    description: 'You have accepted the Tesora DBaaS Platform Terms Of Use'
    type: 'text'
    regex: &tesora_acceptterms_regex
      source: '^I AGREE$'
      error: 'Type "I AGREE" to accept the Tesora Terms Of Use available at http://www.tesora.com/terms-of-use'

  mysql_password:
    label: ""
    description: ""
    type: 'hidden'
    value:
      generator: 'password'
    weight: 101

  admin_password:
    label: ""
    description: ""
    type: 'hidden'
    value:
      generator: 'password'
    weight: 102

  rabbit_password:
    label: ""
    description: ""
    type: 'hidden'
    value:
      generator: 'password'
    weight: 103
